[package]
name = "distant"
description = "Operate on a remote computer through file and process manipulation"
version = "0.1.0"
edition = "2018"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
bytes = "1.0.1"
derive_more = { version = "0.99.16", default-features = false, features = ["display", "from", "error"] }
directories = "3.0.2"
futures = "0.3.16"
hex = "0.4.3"
log = "0.4.14"
orion = "0.16.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.64"
strum = { version = "0.21.0", features = ["derive"] }
tokio = { version = "1.9.0", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = { version = "0.6.7", features = ["codec"] }

# Binary-specific dependencies
flexi_logger = "0.18.0"
fork = "0.1.18"
lazy_static = "1.4.0"
structopt = "0.3.22"
whoami = "1.1.2"
